apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: elevate-ds
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: elevate-ds
    spec:
      containers:
      - name: elevate-ds
        image: lowet84/elevate-test
        imagePullPolicy: Always
        ports:
        - containerPort: 1337
        volumeMounts:
        - mountPath: "/app/API"
          name: volume
      volumes:
      - name: volume
        hostPath:
          path: /elevate
---
apiVersion: v1
kind: Service
metadata:
  name: elevate-ds
  namespace: default
spec:
  ports:
  - port: 1337
    name: "web"
  selector:
    app: elevate-ds
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elevate-ds
  namespace: default
spec:
  rules:
  - host: ds.elevate.se
    http:
      paths:
      - backend:
          serviceName: elevate-ds
          servicePort: 1337
